import streamlit as st
import cv2
import imagehash
from PIL import Image
import os
import numpy as np
from duckduckgo_search import DDGS

# === CONFIGURATION ===
MOCK_INTERNET_FOLDER = "mock_internet"
TAKEDOWN_FOLDER = "takedown_notices"
TARGET_FILENAME = "target_temp.jpg"  # We save the upload here to compare later

# Ensure folders exist
os.makedirs(MOCK_INTERNET_FOLDER, exist_ok=True)
os.makedirs(TAKEDOWN_FOLDER, exist_ok=True)

# === CYBER UI THEME (Improvement 3) ===
st.set_page_config(page_title="ViralTracker Pro", layout="wide")

st.markdown("""
    <style>
    /* Dark Matrix-like Background */
    .stApp {
        background-color: #0d1117;
        color: #00FF41;
        font-family: 'Courier New', Courier, monospace;
    }
    
    /* Neon Green Buttons */
    .stButton>button {
        color: #0d1117;
        background-color: #00FF41;
        border: 1px solid #00FF41;
        font-weight: bold;
        transition: all 0.3s ease;
    }
    .stButton>button:hover {
        background-color: #0d1117;
        color: #00FF41;
        box-shadow: 0 0 10px #00FF41;
    }

    /* Input Fields */
    .stTextInput>div>div>input {
        color: #00FF41;
        background-color: #161b22;
        border: 1px solid #30363d;
    }

    /* Images with Glowing Borders */
    img {
        border: 2px solid #00FF41;
        box-shadow: 0 0 15px rgba(0, 255, 65, 0.3);
        border-radius: 5px;
    }
    
    /* Headers */
    h1, h2, h3 {
        color: #00FF41 !important;
        text-shadow: 0 0 5px rgba(0, 255, 65, 0.5);
    }
    </style>
    """, unsafe_allow_html=True)

# === CORE FUNCTIONS ===

def compute_phash(image_path):
    """Generates a perceptual hash from a file path."""
    img = Image.open(image_path)
    return imagehash.phash(img)

def generate_diff_heatmap(original_path, leaked_path):
    """
    (Improvement 1) Computes the visual difference between the original and the leak.
    Returns a heatmap image array.
    """
    # Load images
    img1 = cv2.imread(original_path)
    img2 = cv2.imread(leaked_path)
    
    if img1 is None or img2 is None:
        return None

    # Resize leak to match original exactly (required for pixel-by-pixel diff)
    img2 = cv2.resize(img2, (img1.shape[1], img1.shape[0]))
    
    # Compute absolute difference
    diff = cv2.absdiff(img1, img2)
    
    # Convert to grayscale mask then to heatmap
    mask = cv2.cvtColor(diff, cv2.COLOR_BGR2GRAY)
    # Apply high contrast to the mask to make small edits visible
    mask = cv2.normalize(mask, None, alpha=0, beta=255, norm_type=cv2.NORM_MINMAX)
    heatmap = cv2.applyColorMap(mask, cv2.COLORMAP_JET)
    
    return heatmap

def scan_local_simulation(target_phash, threshold=10):
    """Scans the local 'mock_internet' folder."""
    matches = []
    for root, dirs, files in os.walk(MOCK_INTERNET_FOLDER):
        for file in files:
            if file.lower().endswith(('.png', '.jpg', '.jpeg')):
                full_path = os.path.join(root, file)
                try:
                    web_img = Image.open(full_path)
                    web_hash = imagehash.phash(web_img)
                    diff = target_phash - web_hash
                    if diff <= threshold:
                        matches.append({
                            "source": "Simulated Web",
                            "url": full_path,
                            "similarity": f"Critical Match (Diff: {diff})"
                        })
                except:
                    continue
    return matches

def scan_external_web(query):
    """Scans DuckDuckGo."""
    matches = []
    try:
        results = DDGS().text(query, max_results=5)
        for res in results:
            matches.append({
                "source": "Real Web (DDG)",
                "url": res['href'],
                "similarity": "Metadata Match"
            })
    except Exception as e:
        st.error(f"External search error: {e}")
    return matches

def generate_takedown(url, reason):
    """Generates a text file notice."""
    filename = f"NOTICE_{abs(hash(url))}.txt"
    path = os.path.join(TAKEDOWN_FOLDER, filename)
    content = f"TAKEDOWN NOTICE\nTarget: {url}\nReason: {reason}\nGenerated by ViralTracker."
    with open(path, "w") as f:
        f.write(content)
    return path

def delete_local_record(file_path):
    try:
        os.remove(file_path)
        return True
    except:
        return False

# === MAIN APP LOGIC ===

st.title("🕵️ VIRAL TRACKER // CYBER OPS")
st.markdown("**SYSTEM STATUS:** ONLINE | **NETWORK:** LOCALHOST")

# Sidebar
mode = st.sidebar.radio("COMMAND CONSOLE", ["1. UPLOAD & SIGNATURE", "2. GLOBAL SCAN", "3. ENFORCEMENT & FORENSICS"])

if "target_hash" not in st.session_state:
    st.session_state.target_hash = None
if "matches" not in st.session_state:
    st.session_state.matches = []

# --- TAB 1: UPLOAD ---
if mode == "1. UPLOAD & SIGNATURE":
    st.header("Step 1: Ingest Target Data")
    uploaded_file = st.file_uploader("Upload Image Asset", type=['jpg', 'png'])
    
    if uploaded_file:
        col1, col2 = st.columns(2)
        with col1:
            st.image(uploaded_file, caption="Target Asset", width=300)
        with col2:
            if st.button("GENERATE HASH SIGNATURE"):
                # Save file locally for Heatmap usage later
                with open(TARGET_FILENAME, "wb") as f:
                    f.write(uploaded_file.getbuffer())
                
                st.session_state.target_hash = compute_phash(TARGET_FILENAME)
                st.success(f"HASH LOCK ACQUIRED: {st.session_state.target_hash}")
                st.code(f"SHA-256 (Visual): {st.session_state.target_hash}", language="bash")

# --- TAB 2: SCAN ---
elif mode == "2. GLOBAL SCAN":
    st.header("Step 2: Threat Detection")
    
    if not st.session_state.target_hash:
        st.warning("⚠️ NO TARGET LOCKED. RETURN TO STEP 1.")
    else:
        st.write(f"Searching for signature: `{st.session_state.target_hash}`")
        
        col1, col2 = st.columns(2)
        with col1:
            st.subheader("Local Network Simulation")
            if st.button("INITIATE LOCAL SCAN"):
                local_hits = scan_local_simulation(st.session_state.target_hash)
                st.session_state.matches.extend(local_hits)
                if local_hits:
                    st.success(f"⚠️ THREATS DETECTED: {len(local_hits)}")
                else:
                    st.info("System Clear.")
        
        with col2:
            st.subheader("External Web Grid")
            search_query = st.text_input("Keywords (e.g. 'leaked confidential'):")
            if st.button("INITIATE WEB CRAWL"):
                if search_query:
                    web_hits = scan_external_web(search_query)
                    st.session_state.matches.extend(web_hits)
                    st.success(f"⚠️ LINKS FOUND: {len(web_hits)}")

        # Results Display
        if st.session_state.matches:
            st.divider()
            st.subheader("🚨 LIVE FEED")
            for match in st.session_state.matches:
                st.error(f"[{match['source']}] >> {match['url']}")

# --- TAB 3: ENFORCEMENT ---
elif mode == "3. ENFORCEMENT & FORENSICS":
    st.header("Step 3: Neutralization & Forensics")
    
    if not st.session_state.matches:
        st.write("No active threats.")
    else:
        for i, match in enumerate(st.session_state.matches):
            st.markdown(f"### 🚩 THREAT #{i+1}")
            st.code(match['url'])
            
            c1, c2, c3 = st.columns(3)
            
            # Button 1: Takedown
            with c1:
                if st.button(f"📄 GENERATE NOTICE #{i+1}"):
                    path = generate_takedown(match['url'], "Copyright Infringement")
                    st.success(f"Notice Saved: {path}")

            # Button 2: Forensic Heatmap (Local Only)
            with c2:
                if "mock_internet" in match['url']:
                    if st.button(f"🔍 RUN FORENSICS #{i+1}"):
                        if os.path.exists(TARGET_FILENAME):
                            # Generate Heatmap
                            heatmap = generate_diff_heatmap(TARGET_FILENAME, match['url'])
                            if heatmap is not None:
                                st.image(heatmap, caption="MODIFICATION HEATMAP (Red = Altered)", channels="BGR", clamp=True)
                                st.info("Visual analysis complete. Red areas indicate manipulation.")
                            else:
                                st.error("Error reading image data.")
                        else:
                            st.warning("Original target file lost. Please re-upload in Step 1.")
                else:
                    st.caption("Forensics unavailable for external URLs")

            # Button 3: Delete (Local Only)
            with c3:
                if "mock_internet" in match['url']:
                    if st.button(f"🗑️ PURGE FILE #{i+1}"):
                        if delete_local_record(match['url']):
                            st.error("ASSET PURGED FROM SERVER.")
                        else:
                            st.warning("Deletion Failed.")
            
            st.divider()